// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cubsudtoiqsdneecrjkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1YnN1ZHRvaXFzZG5lZWNyamt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzExMzAsImV4cCI6MjA2NTQwNzEzMH0.6IpwLaqvW_Oml2K_dbB2wAaYRp4rxB_ZWnKnAluy_mE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);