import { CheckCircle, FileCheck, Send, Users, Shield, Eye, CreditCard, ClipboardList, Layers, Wrench, PackageCheck } from 'lucide-react';

export const statusOptions = [
  {
    value: 'BA Joint Inspection',
    label: 'BA Joint Inspection',
    color: 'bg-sky-100 text-sky-800 border-sky-300',
    icon: Layers,
    step: 1,
    repeatable: true,
  },
  {
    value: 'BA Commissioning',
    label: 'BA Commissioning',
    color: 'bg-teal-100 text-teal-800 border-teal-300',
    icon: Wrench,
    step: 2,
    repeatable: true,
  },
  {
    value: 'BA Penerimaan Material',
    label: 'BA Penerimaan Material',
    color: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    icon: PackageCheck,
    step: 3,
    repeatable: true,
  },
  {
    value: 'LKP',
    label: 'LKP',
    color: 'bg-gray-100 text-gray-800 border-gray-300',
    icon: ClipboardList,
    step: 4,
  },
  {
    value: 'BASTP',
    label: 'BASTP',
    color: 'bg-orange-100 text-orange-800 border-orange-300',
    icon: FileCheck,
    step: 5,
  },
  {
    value: 'BAKP/BAPP',
    label: 'BAKP / BAPP',
    color: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    icon: Send,
    step: 6,
  },
  {
    value: 'Submit i-Vendor',
    label: 'Submit i-Vendor',
    color: 'bg-blue-100 text-blue-800 border-blue-300',
    icon: Users,
    step: 7,
  },
  {
    value: 'SA',
    label: 'SA',
    color: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: Shield,
    step: 8,
  },
  {
    value: 'PA',
    label: 'PA',
    color: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: Eye,
    step: 9,
  },
  {
    value: 'Verification',
    label: 'Verification',
    color: 'bg-pink-100 text-pink-800 border-pink-300',
    icon: CheckCircle,
    step: 10,
  },
  {
    value: 'Payment/Selesai',
    label: 'Payment / Selesai',
    color: 'bg-green-100 text-green-800 border-green-300',
    icon: CreditCard,
    step: 11,
  },
];